// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace coursedb.Data.db
{
    public partial class Types
    {
        public Types()
        {
            Orders = new HashSet<Orders>();
        }

        public int Typeid { get; set; }
        public string Typename { get; set; }
        public short Billedper { get; set; }
        public int Price { get; set; }

        public virtual ICollection<Orders> Orders { get; set; }
    }
}